name: kybele_gen2
description: Second generation of Kybele app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  youtube_player_flutter: ^8.1.0
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
  provider: ^6.0.3
  path: ^1.8.2
  pdfx: ^2.3.0
  vibration: ^1.7.6
  flutter_ringtone_player: ^3.2.0
  intl: ^0.17.0
  go_router: ^6.0.2
  auto_size_text: ^3.0.0
  shared_preferences: ^2.0.18
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/NunitoSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/NunitoSans-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/NunitoSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/NunitoSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/NunitoSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/NunitoSans-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/NunitoSans-BlackItalic.ttf
          style: italic
          weight: 900
