// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG6OR-Gr6GSwRdHs6etrlVQeTiXMMmPwE',
    appId: '1:339132272891:web:1d50f449369df569da205e',
    messagingSenderId: '339132272891',
    projectId: 'kybele-gen2',
    authDomain: 'kybele-gen2.firebaseapp.com',
    storageBucket: 'kybele-gen2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jCXOcGtAvxSDYMOVm1j4VYIwoaD0uGg',
    appId: '1:339132272891:android:debda091166bc875da205e',
    messagingSenderId: '339132272891',
    projectId: 'kybele-gen2',
    storageBucket: 'kybele-gen2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdATmQfi43ZH7VRiBqfW6-1hgS8wXE_Rk',
    appId: '1:339132272891:ios:ef14b70c02ca083bda205e',
    messagingSenderId: '339132272891',
    projectId: 'kybele-gen2',
    storageBucket: 'kybele-gen2.appspot.com',
    iosClientId: '339132272891-cdk5htdshvmm6jrqmm1juhse3ljc5ngt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kybeleGen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdATmQfi43ZH7VRiBqfW6-1hgS8wXE_Rk',
    appId: '1:339132272891:ios:ef14b70c02ca083bda205e',
    messagingSenderId: '339132272891',
    projectId: 'kybele-gen2',
    storageBucket: 'kybele-gen2.appspot.com',
    iosClientId: '339132272891-cdk5htdshvmm6jrqmm1juhse3ljc5ngt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kybeleGen2',
  );
}
